base_images:
  base:
    name: "4.14"
    namespace: ocp
    tag: base
binary_build_commands: make -f openshift-ci/Makefile build
build_root:
  project_image:
    dockerfile_path: openshift-ci/Dockerfile.tests
images:
- dockerfile_path: openshift-ci/Dockerfile.tests
  from: base
  to: helm
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tests:
- as: helm-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
    test:
    - as: helm-acceptance-test
      commands: make -f openshift-ci/Makefile build test-acceptance
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: release-3.11
  org: redhat-developer
  repo: helm
  variant: helm-ocp4.14-lp-interop
